#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewTutorial.Resource", IsApplication=true)]

namespace ListViewTutorial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_app = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_locate = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_map = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_new = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_new_picture = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_refresh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_save = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int actionDelete = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int actionNew = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int actionRefresh = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int actionSave = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int artistEditText = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int artistTextView = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int connectServerButton = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int nameTextView = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int playPauseButton = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout1 = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int scrollView1 = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int serverIpText = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int serverPassText = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int serverPortText = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int songListView = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int stopButton = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int titleEditText = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int txtName = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int listview_row = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ServerConnectionLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SongDetail = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SongList = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SongListItem = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int SongDetailMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int SongListView = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
